# email: echo "knoopx@gmail.com"
# downloads$dir: echo "~/Downloads"

config: echo "$HOME/.config/shamls/config.yaml"

hackernews:
  default: xdg-open "<pick-frontpage-url>"
  list-frontpage-items:
  pick-frontpage-url: echo "<list-frontpage-items>" | fzf --ansi --multi --highlight-line --layout reverse | tail -n 1

search:
  text: gum input --placeholder "search..."

  nixpkgs: xdg-open "https://search.nixos.org/packages?channel=unstable&type=packages&query=<text>"
  github: xdg-open "https://github.com/search?type=repositories&q=<text>"

  duck-duck-go:
    default: xdg-open "<pick>"
    pick: |
      ddgr --json --noprompt --expand "<text>" \
        | jq -rc '. | map("{{ Color \"99\" \"\(.title)\" }}\n\(.abstract)\n\(.url)\n") | .[]' \
        | gum format -t template \
        | perl -0 -pe 's/\n\n/\0/gm' \
        | fzf --read0 --ansi --multi --highlight-line --layout reverse \
        | tail -n 1

ollama:
  api: echo "http://localhost:11434/api"
  list-models: gum spin --spinner dot --title "Loading model list..." -- curl --silent "<api>/tags" | jq -r '.models[].name' | sort
  pick-model: echo "<list-models>" | gum choose --selected "$(skate get ollama-model)"
  text: gum write --placeholder "prompt..."

  default: |
    ollamark -m "<pick-model>" "<text>"
    skate set ollama-last "<text>"
    skate set ollama-model "<pick-model>"

  last-prompt: skate get ollama-last
  re-ask: |
    prompt=$(gum write --placeholder "prompt..." --prompt "<last-prompt>")
    skate set ollama-last "$prompt"
    skate set ollama-model "<model>"
    ollamark -m "<model>" "$prompt"

# applications:
#   default: find /etc/profiles/per-user/knoopx/share/applications -iname "*.desktop" | xargs -L 1 basename

clipboard:
  +clipboard-actions: shamls "<config>" <action>
  action: echo "<input>" | fzf --ansi --multi --highlight-line --layout reverse | head -n 1
  input: shamls "<config>" --text "$(wl-paste)"

text:
  +text-actions: shamls "<config>" <pick-action>
  +ask-ollama: shmls "<config>" $ollama.run --text "<text>"
  +text-to-speech: tts "<text>"

  pick-action: echo "<input>" | fzf --ansi --multi --highlight-line --layout reverse | head -n 1
  input: shamls "<config>" --text "$(gum write --placeholder "text")"

caffeine:
  +caffeinate: gsettings --schemadir /etc/profiles/per-user/$USER/share/gnome-shell/extensions/caffeine@patapon.info/schemas/ set org.gnome.shell.extensions.caffeine toggle-state true
  +decaffeinate: gsettings --schemadir /etc/profiles/per-user/$USER/share/gnome-shell/extensions/caffeine@patapon.info/schemas/ set org.gnome.shell.extensions.caffeine toggle-state false

utility:
  +ansi-colors: echo "<print-ansi-colors> | gum pager"
  +generate-random-token: tr -dc A-Za-z0-9$ < /dev/urandom | head -c 32 | xargs  | gum pager

  print-ansi-colors: |
    for fgbg in 38 48 ; do
        for color in {0..256} ; do
            echo -en "\e[${fgbg};5;${color}m ${color}\t\e[0m"
            if (( $((($color + 1) % 6)) == 0 )) ; then
                echo ""
            fi
        done
    done

download:
  pick-file: gum file
  +from-list: cat "<pick-file>" | aria2c --continue=true --auto-file-renaming=false -i -c

# global:
#   clipboard: list-actions --text "{pbpaste}" | fuzzy
#   hacker-news: run-action hacker-news | fuzzy
#   downloads: find <downloads$dir>

music:
  :play-album: amberol "$(find "<pick-album>" -iname "*.mp3")"

  path: echo "/mnt/junk/Music"
  list-albums: find "<path>" -iname "*.mp3" -print0 | xargs -0 dirname | uniq
  pick-album: echo "<list-albums>" | gum filter

igir:
  +move-roms: npx -y igir move --dir-dat-name --dat "<dat>" --input <input> --output <output>

  roms-dir: echo "/mnt/junk/Roms"
  dats-dir: echo "~/.local/share/dats"

  input-dirs: |
    echo "<downloads$dir>"
    echo "<roms-dir>"
    echo $PWD

  output-dirs: |
    echo "<input>"
    echo "<roms-dir>"
    echo $PWD

  pick-dat: find -L <dats-dir> | gum filter
  input: echo "<input-dirs>" | sort -u | gum filter
  output: echo "<output-dirs>" | sort -u | gum filter

firefox:
  db: echo "$HOME/.mozilla/firefox/knoopx/places.sqlite"
  list-bookmarks: |
    tmp=$(mktemp)
    cp "<db>" "$tmp"
    sqlite3 "$tmp" "SELECT DISTINCT mb.title || CHAR(10) || mp.url FROM moz$bookmarks mb INNER JOIN moz$places mp ON mp.id = mb.fk WHERE mb.type = 1 AND mb.title IS NOT NULL ORDER BY mp.frecency DESC"
    rm "$tmp"
  +open-bookmark: |
    xdg-open "$(echo "$(echo "<list-bookmarks>" \
      | awk -F'\t' 'NR % 2 == 0 { printf "\033[30m%s\033[0m\0", $1; } NR % 2 != 0 { printf "\033[1;37m%s\033[0m\n", $1;}' \
      | fzf --read0 --ansi --multi --highlight-line --layout reverse)" | tail -n1)"

  # history: |
  #   tmp=$(mktemp)
  #   cp "<db>" "$tmp"
  #   sqlite3 "$tmp" "SELECT DISTINCT title || CHAR(10) || url FROM moz$places WHERE title IS NOT NULL ORDER BY last$visit$date DESC"
  #   rm "$tmp"
  # asd: |
  #   echo "<history>"
  # \
  #   | awk -F'\t' 'NR % 2 == 0 { printf "\033[30m%s\033[0m\0", $1; } NR % 2 != 0 { printf "\033[1;37m%s\033[0m\n", $1;}'
  # | fzf --read0 --ansi --multi --highlight-line --layout reverse)" | tail -n1
  # xdg-open "$(echo "$()"

docker:
  containers: sudo docker ps | sed '1d'
  container: echo "<containers>" | gum choose | awk '{print $1}'
  +shell: sudo docker exec -ti "<container>" "/bin/sh"
  +logs: sudo docker logs -f "<container>"
  +prune: sudo docker system prune -a

google-calendar:
  +month: gum spin --spinner dot --title "Fetching..." -- reset; gcalcli calm --monday --military --width 15 | less -r
  +week: gum spin --spinner dot --title "Fetching..." -- reset; gcalcli calw --monday --military | less -r
  +agenda: gum spin --spinner dot --title "Fetching..." -- reset; gcalcli agenda | less -r

systemd:
  list-units: systemctl --user --full --no-legend --no-pager list-unit-files
  unit: echo "<list-units>" | gum filter | awk '{print $1}'

  +start: systemctrl start "<unit>"
  +stop: systemctrl stop "<unit>"
  +restart: systemctrl restart "<unit>"
  +logs: journalctl --user -u "<unit>"

launcher:
  list-actions: shamls "<config>"
  # actions: shamls "<config>" | perl -0 -pe 's/\n\n/\0/gm' | fzf --read0 --ansi --multi --highlight-line --layout reverse --with-nth 1
  pick-action: echo "<list-actions>" | fzf --columns --ansi --multi --highlight-line --layout reverse --with-nth 1 --delimiter "\t"
  # pick-action: echo "<list-actions>" | sort | fzf --ansi --multi --highlight-line --layout reverse | head -n 1
  run-action: shamls "<config>" "$(shamls "<config>" launcher.pick-action)"
# GoogleCalendar:
#   MonthCalendar: gum spin --spinner dot --title "Fetching..." -- reset; gcalcli calm --monday --military --width 15 | less -r
#   WeekCalendar: gum spin --spinner dot --title "Fetching..." -- reset; gcalcli calw --monday --military | less -r
#   Agenda: gum spin --spinner dot --title "Fetching..." -- reset; gcalcli agenda | less -r

# $Launcher:
#   ListActions: shamls "<config>"
#   # | grep -v -r "^$"
#   PickAction: echo "<ListActions>" | fzf --ansi --multi --highlight-line --layout reverse | head -n 1
#   RunAction: shamls "<config>" "$(shamls "<config>" "$Launcher.PickAction")"
